# Generated by Django 3.1.1 on 2020-09-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200915_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='descForCard',
            field=models.CharField(default='', max_length=500),
        ),
    ]
